default:
  navigation:
    - title: Noodles
      subtitle: Categories
      url: /t/noodles
      items:
        - :title: Instant
          :url: /t/noodles/instant
        - :title: Dried
          :url: /t/noodles/dried
        - :title: fresh
          :url: /t/noodles/fresh
      promo_banners:
        - subtitle: Special Offers
          title: Summer 2019
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Sale
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: Snacks
      subtitle: Categories
      url: /t/snacks
      items:
        - :title: Chips
          :url: /t/snacks/chips
        - :title: Biscuit
          :url: /t/snacks/Biscuit
        - :title: Sweets
          :url: /t/snacks/sweets
        - :title: Jelly
          :url: /t/snacks/jelly
      promo_banners:
        - subtitle: New collection
          title: Summer 2019
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-second-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-second-category.jpg'
    - title: Rice/Flour
      subtitle: Categories
      url: /t/rice-flour
      items:
        - :title: rice
          :url: /t/rice-flour/rice
        - :title: flour
          :url: /t/rice-flour/flour
      promo_banners:
        - subtitle: New collection
          title: Summer 2019
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-third-category.jpg'
    - title: Sauce
      subtitle: Categories
      url: /t/sauce
      items:
        - :title: chilli
          :url: /t/sauce/chilli
        - :title: fish
          :url: /t/sauce/fish
        - :title: soy
          :url: /t/sauce/soy
        - :title: Satay
          :url: /t/sauce/satay
      promo_banners:
        - subtitle: New collection
          title: Summer 2019
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-third-category.jpg'
    - title: Drinks
      subtitle: Categories
      url: /t/drinks
      items:
        - :title: canned
          :url: /t/drinks/canned
        - :title: Tea
          :url: /t/drinks/tea
        - :title: Coffee
          :url: /t/drinks/coffee
        - :title: bulk
          :url: /t/drinks/bulk
      promo_banners:
        - subtitle: New collection
          title: Summer 2019
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-second-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-second-category.jpg'
    - title: Canned
      subtitle: Categories
      url: /t/canned
      items:
        - :title: meat
          :url: /t/canned/meat
        - :title: fruits
          :url: /t/canned/fruits
        - :title: vegetable
          :url: /t/canned/vegetable
      promo_banners:
        - subtitle: New collection
          title: Summer 2019
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-third-category.jpg'
    - title: Spices
      subtitle: Categories
      url: /t/spices
      items:
        - :title: herbs
          :url: /t/spices/herbs
        - :title: seafood
          :url: /t/spices/seafood
        - :title: seasoning
          :url: /t/spices/seasoning
