default:
  navigation:
    - title: Personal Care
      subtitle: Categories
      url: /t/personal-care
      items:
        - :title: Cleanser
          :url: /t/personal-care/Cleanser
        - :title: Moisturiser
          :url: /t/personal-care/Moisturiser
        - :title: Essence/Serum/Ampoule
          :url: /t/personal-care/Essence
        - :title: Toner
          :url: /t/personal-care/Toner
        - :title: Masks/Packs
          :url: /t/personal-care/Masks
        - :title: Patches
          :url: /t/personal-care/patches
        - :title: Sets/Gifts
          :url: /t/personal-care/Sets
      promo_banners:
        - subtitle: New collection
          title: Summer 2019
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: Men
      subtitle: Categories
      url: /t/men
      items:
        - :title: Shirts
          :url: /t/men/shirts
        - :title: T-shirts
          :url: /t/men/t-shirts
        - :title: Sweaters
          :url: /t/men/sweaters
        - :title: Jackets and Coats
          :url: /t/men/jackets-and-coats
      promo_banners:
        - subtitle: New collection
          title: Summer 2019
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-second-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-second-category.jpg'
    - title: Sportswear
      subtitle: Categories
      url: /t/sportswear
      items:
        - :title: Tops
          :url: /t/sportswear/tops
        - :title: Sweatshirts
          :url: /t/sportswear/sweatshirts
        - :title: Pants
          :url: /t/sportswear/pants
      promo_banners:
        - subtitle: New collection
          title: Summer 2019
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-third-category.jpg'
